# Generated by Django 4.2.7 on 2024-01-04 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_pw_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(blank=True, default=0, related_name='user_privileges', to='login.user')),
            ],
        ),
        migrations.RenameField(
            model_name='accesslevel',
            old_name='level_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='occupation',
            old_name='type_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='accesslevel',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to='login.user'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citystate',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_city_state', to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupation',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_occupation', to='login.user'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
