# Generated by Django 4.2.7 on 2024-01-04 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_user_password_remove_user_pw_reset_userpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslevel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='citystate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='citystate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='citystate',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='citystate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userpass',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userpass',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userpass',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userpass',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprivileges',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=3, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citystate',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=3, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=3, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpass',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=3, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Zipcode',
        ),
    ]
