# Generated by Django 4.2.7 on 2024-01-05 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_address_user_ptr_remove_citystate_user_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='login.address')),
                ('city_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_city_state', to='login.citystate')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to='login.accesslevel')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_occupation', to='login.occupation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='login.user')),
            ],
        ),
    ]
