# Generated by Django 4.2.7 on 2024-01-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='phone',
            field=models.ForeignKey(default=5555555555, on_delete=django.db.models.deletion.CASCADE, related_name='user_phone', to='login.phone'),
            preserve_default=False,
        ),
    ]
