# Generated by Django 4.2.7 on 2024-01-05 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_user_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to='login.user'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='login.user'),
        ),
        migrations.AlterField(
            model_name='citystate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_city_state', to='login.user'),
        ),
        migrations.AlterField(
            model_name='userpass',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_password', to='login.user'),
        ),
    ]
