# Generated by Django 4.2.7 on 2024-01-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_accesslevel_user_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(default='mobile', max_length=50),
        ),
    ]
