# Generated by Django 4.2.7 on 2024-01-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_phone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='citystate',
            name='zipcode',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
