# Generated by Django 4.2.7 on 2024-01-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_citystate_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslevel',
            name='user',
        ),
        migrations.AlterField(
            model_name='accesslevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='access_level', to='login.accesslevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to='login.user')),
            ],
        ),
    ]
