# Generated by Django 4.2.7 on 2024-01-05 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_accesslevel_user_alter_accesslevel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='access_level', to='login.accesslevel'),
        ),
    ]
