# Generated by Django 4.2.7 on 2024-01-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_accesslevel_users_delete_userlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_model', models.CharField(max_length=50)),
                ('option_field', models.CharField(max_length=50)),
                ('option', models.CharField(max_length=50)),
                ('option_label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
