# Generated by Django 4.2.7 on 2024-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_formoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formoptions',
            name='option_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='formoptions',
            name='option_model',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
