# Generated by Django 4.2.7 on 2024-01-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_alter_occupation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
