# Generated by Django 4.2.7 on 2024-01-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_email_delete_userpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='number',
            new_name='phone_number',
        ),
    ]
