# Generated by Django 4.2.7 on 2024-01-15 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_rename_number_phone_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='type',
            new_name='phone_type',
        ),
    ]
