# Generated by Django 5.0.7 on 2025-02-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=100)),
                ('file', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'NotSet'), (20, 'Info'), (30, 'Warning'), (10, 'Debug'), (40, 'Error'), (50, 'Critical')], db_index=True, default=40)),
                ('msg', models.TextField()),
                ('trace', models.TextField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'System Logs',
                'verbose_name_plural': 'System Logs',
                'ordering': ('-create_datetime',),
                'indexes': [models.Index(fields=['create_datetime'], name='logger_stat_create__cb33b0_idx')],
            },
        ),
    ]
